name: Publish

on:
    push:
        branches: [main]

jobs:
    publish:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash -l {0}
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: 3.10

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install build twine

            - name: Build package
              run: |
                  python -m build

            - name: Publish package to PyPI
              env:
                  TWINE_USERNAME: __token__
                  TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
              run: |
                  python -m build
                  twine upload --skip-existing dist/*